def category_map():
    return {
    'costco whse': 'groceries',
    'costco gas': 'transportation',
    'pcc': 'groceries',
    'ctrl mkt': 'groceries',
    'trader joe': 'groceries',
    'asian family': 'groceries',
    'camp': 'lifestyle',
    'schlpay': 'school',
    'fred-meyer': 'groceries',
    'barber shop': 'household',
    'swansons nursery': 'household',
    'membership': 'household',
    'bistro': 'restaurant',
    'restaurant': 'restaurant',
    ' bar ': 'restaurant',
    ' pub ': 'restaurant',
    'pizza': 'restaurant',
    'sushi': 'restaurant',
    'verizon': 'comm/media',
    'amzn mktp': 'household',
    'qfc': 'groceries',
    ' salon ': 'household',
    ' grill ': 'restaurant',
    'safeway': 'groceries',
    'albertson': 'groceries',
    'starbucks': 'restaurant',
    'alaska air': 'transportation',
    'netflix': 'comm/media',
    'disneyplus': 'comm/media',
    'arco': 'transportation',
    'home depot': 'household',
    'hardware': 'household',
    'parking': 'transportation',
    'metropolitan mkt': 'groceries',
    'tutta bella': 'restaurant',
    'target': 'household',
    'pink door': 'restaurant',
    'wsdot': 'transportation',
    'boo han': 'groceries',
    'nordstrom': 'household',
    'orca': 'transportation',
    'taqueria': 'restaurant',
    'dollar tree': 'household',
    'lowes': 'household',
    'bartell drug': 'household',
    'walgreen': 'household',
    'at&t': 'comm/media',
    'xfinity': 'comm/media',
    'wholefds': 'groceries',
    'mollie stones': 'groceries',
    'chef wang': 'restaurant',
    'silver house': 'restaurant',
    ' inn ': 'lifestyle',
    'amazon fresh': 'groceries',
    'gainsbourg': 'restaurant',
    '74th street': 'restaurant',
    '76 ': 'transportation',
    'book store': 'household',
    'foresma': 'school',
    'fastrak': 'transportation',
    'true value': 'household',
    'csc serviceworks': 'household',
    'in-n-out': 'restaurant',
    'rei ': 'household',
    "ken's market": 'groceries',
    'valero': 'transportation',
    'big time': 'restaurant'
    }